defaults: 
  - _self_
  - dataset: mutag
  - my_model: mlp_bottleneck
  - dgm: knn_conf  
  - pooling: perceiver
  - training: train_conf
  - exp: snr_conf
  - paths: default



hydra:
  sweeper:
    params:
      # my_model.layers.n_pre: choice(2, 3, 4)
      # my_model.layers.n_post: choice(2, 3, 4)
      # my_model.layers.receiver: choice(2, 3)
      #my_model.dropout: choice(0.1, 0.2)         
      # training.lr: choice(0.001, 0.0005)   
      pooling.pooling_ratio: choice(0.99)
      my_model.layers.n_pre: choice(1, 2, 3)
      my_model.layers.n_post: choice(1, 2, 3)
      my_model.layers.receiver: choice(1, 2, 3)


    