num_features: 37
num_classes: 2
pre_layers:
- 37
- 32
conv_layers:
- 32
post_layers:
- 32
- 2
dgm_layers:
- 32
- 32
lr: 0.005
dgm_name: topk_dgm
gamma: 0
std: 0
k: 0
distance: euclidean
use_gcn: true
dropout: 0.0
ensemble_steps: 1
optimizer: adam
pooling: topk
ratio: 0.9
topk_minscore: 0.1
snr_db: 13
