num_features: 3
num_classes: 2
pre_layers:
- 3
- 32
- 32
conv_layers:
- 32
- 32
- 32
- 32
- 32
- 32
- 32
- 32
post_layers:
- 32
- 2
dgm_layers:
- 32
- 32
- 32
- 32
- 32
lr: 0.005
gamma: 50
std: 0.0
use_gcn: true
dropout: 0.0
ensemble_steps: 1
optimizer: adam
ratio: 0.3
topk_minscore: 0.1
snr_db: 13
