num_features: 4
num_classes: 2
pre_layers:
- 4
- 32
- 32
conv_layers:
- 32
post_layers:
- 32
- 2
dgm_layers:
- 32
- 32
lr: 0.05
dgm_name: alpha_dgm
gamma: 0
std: 0
k: 0
distance: euclidean
use_gcn: true
dropout: 0.0
ensemble_steps: 1
optimizer: adam
pooling: topk
ratio: 0.9
topk_minscore: 0.1
snr_db: 13
