
metric:
  name: train_loss
  goal: minimize

seed: 42
data_seed: 0

layers: 
  hsize: 32
  n_pre: 2
  n_post: 2
  n_conv: 2
  n_dgm_layers: 3
  receiver: 2


dropout: 0.0
use_gcn: true


channel:
  noise: 'awgn'
  snr_db: 13

graph_loss_reg: 1
poly_loss_reg: 1
ensemble_steps: 1

skip_connection: True

