name: 'dgm_channel'

metric:
  name: train_loss
  goal: minimize

seed: 42
data_seed: 0

layers: 
  hsize: 32
  n_pre: 3
  n_post: 2
  n_conv: 5
  n_dgm_layers: 3
  receiver: 3


dropout: 0.0
use_gcn: false


channel:
  noise: 'awgn'
  snr_db: null

graph_loss_reg: 1
poly_loss_reg: 1
ensemble_steps: 1

skip_connection: True

