
metric:
  name: train_loss
  goal: minimize

seed: 42
data_seed: 0

layers: 
  hsize: 32
  n_pre: 1
  n_post: 1
  n_conv: 1
  n_dgm_layers: 1


dropout: 0.0
use_gcn: true

#k: 4


channel:
  noise: 'awgn'
  snr_db: 13

graph_loss_reg: 1
poly_loss_reg: 1
ensemble_steps: 1

